[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "example_package_rmkane"
version = "0.0.2"
authors = [
    { name = "Ryan Kane", email = "rmkane@proton.me" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/rmkane/packaging_tutorial"
Issues = "https://github.com/rmkane/packaging_tutorial/issues"
